# Options for analysis running.
run:
  # See the dedicated "run" documentation section.
  option: value
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 10m
# output configuration options
output:
  # See the dedicated "output" documentation section.
  option: value
# All available settings of specific linters.
linters-settings:
  # See the dedicated "linters-settings" documentation section.
  option: value
linters:
  # See the dedicated "linters" documentation section.
  option: value
  enable-all: true
  disable:
    - exhaustivestruct # The owner seems to have abandoned the linter.  Replaced by exhaustruct.
    - scopelint # The repository of the linter has been deprecated by the owner.  Replaced by exportloopref
    - golint # The repository of the linter has been archived by the owner.  Replaced by revive.
    - maligned # The repository of the linter has been archived by the owner.  Replaced by govet 'fieldalignment
    - interfacer # The repository of the linter has been archived by the owner.
    - ifshort # The repository of the linter has been deprecated by the owner
    - dupl # too many false positives
    - tagliatelle # too many false positives
    - gci # conflicting with goimports order
    - exhaustruct # almost useless
    - varnamelen # way to many false positives
issues:
severity:
  # See the dedicated "severity" documentation section.
  option: value
