version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-all-in-one-test
    restart: on-failure
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - JAEGER_USER=jaeger
      - JAEGER_PASSWORD=jaeger
  postgres:
    image: postgres:latest
    container_name: postgres-test
    restart: on-failure
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=common"
    ports:
      - "5433:5432"
    command: ["postgres", "-c", "log_statement=all"]
  postgres-migrations:
    image: postgres:latest
    container_name: postgres-migrations-test
    restart: on-failure
    volumes:
      - ./zeromigrations:/zeromigrations
    command: bash -c "chmod -fR 0777 /zeromigrations && /zeromigrations/migrate.sh"
    links:
      - postgres

  app:
    image: golang:1.19
    container_name: app-test
    restart: on-failure
    volumes:
        - ./:/app
    working_dir: /app
    environment:
      - CONNECTION_STRING=postgresql://postgres:postgres@postgres:5432/common?sslmode=disable
      - JAEGER_ENDPOINT=http://jaeger:jaeger@jaeger:14268/api/traces
      - JAEGER_PASSWORD=jaeger
      - JAEGER_USER=jaeger
      - JAEGER_SERVICE_NAME=casa
    command: ["go", "run", "./cmd/main.go"]
    links:
      - postgres
      - jaeger


  nginx:
    image: nginx:stable-alpine
    container_name: nginx-test
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    command: sh -c "apk add openssl && openssl req -x509 -nodes -days 365 -subj \"/C=CA/ST=QC/O=Company, Inc./CN=seamless.example.com\" -addext \"subjectAltName=DNS:seamless.example.com\" -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt && nginx -g \"daemon off;\";"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/seamless-ca.pem:/nginx/seamless-ca.pem
      - ./swagger:/usr/share/nginx/html/swagger
    links:
      - app